### ISSUE TITLE
Feature Request : Multi Currency Support

### ISSUE THREAD

**Issue by Hari-Bonda** [flamarkt/core#2]
Consider adding Multi-Currency Support and currency switcher, i hope this is already in your todo list

to know more visit https://wordpress.org/plugins/currency-switcher/

**Comment by clarkwinkelmann** [comment]
Thanks for the suggestion. This is not something I am working on at the moment.

The feature described in that Wordpress plugin seems like perfect fit for a future third-party Flamarkt extension. It probably doesn't even need any special extension API to work if it's just a readonly or even client-side-only information. The money label is already an extendable component in the current dev version.

The ability to collect money in multiple currencies or list some products in other currencies will also likely be possible with the extension API, but that's also not a planned core extension at the moment.

The core package will only have the number of price decimals and currency label configurable. Decimals are currently hard-coded to 2 and label is currently hard-coded to CHF but both will be customizable in the initial release.

I'm closing this issue as it would otherwise stay open forever. The discussion on the forum might be a better place for suggestions https://discuss.flarum.org/d/28059-flamarkt-its-not-here-yet
